language: node_js
cache: yarn
notifications:
  email: false
node_js:
- stable
deploy:
  provider: npm
  email: james@faceyspacey.com
  api_key:
    secure: X1/dlUS44OcX1udCZpW7F6DZcnL02dU0l2rDz8IKcj67CBLPOHaAOp6jmth+gVFRy1KlDlSD/L/vJ8sEeZcSpDzwcT8gSPodyVdwb0uvsKEqWM90Rn9Sgp7S/U/O09aN57aNnrFIKJftA+Wy4GX1a4U5GJc034EM7sJARIajuHR+w3XFej9O9/aOAJcOEbpqgzWOQwt/d1BW5Qa5lrqTnGsjgqlMD9zHUMXyS9mOAh+gAmBtEw6q73dbdpPdMgf1u1HqFSm+G7E4tsp1fX3ztpQiu2hwnpiQHZafDRnNstllmKKMMEYolBufLpd5w5FrlbyDAICENiqQtvQXwJiEWe3UhJWcaq5IgCaVyTDvACrXWuBLsC3evEUaSGA3bPmJXkrDsETRupmitmV8iXskK22XfQ/hSQgxoz4FekuRqJcApAwhNxFciNm5j+wiAUT/ZA4UqaupUQLDLYu1+bLJsVxE+FT3una7iJS1mnboPZbXEYFxjkxMbEjDx6ZX2IrAMwxFf7e1g3U6jU/hqecMlZRsM/Dw1bAVjKtilGTtcxlYnYLKGDGPTMzOVtnia58ZbqKUOfws9KuJIEYYTuCCCws7eWBh2bvzIqtzEET+n/D3T0lsaohCHkV7FPKYBj3eSjZbXJSTB2dTXffhoWls4hKgfwFWJTNaO0hq59lKvuU=
  on:
    tags: true
    repo: faceyspacey/webpack-server-middleware
